services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: N8N_ENVIRONMENT
        value: "production"
      - key: N8N_HOST
        value: "n8nselfhost-render.onrender.com"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8nselfhost-render.onrender.com"
      - key: GENERIC_TIMEZONE
        value: "Asia/Bangkok"
