services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_ENVIRONMENT
        value: "production"
      - key: N8N_HOST
        value: "n8nselfhost-render.onrender.com"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8nselfhost-render.onrender.com"
      - key: WEBHOOK_URL
        value: "https://n8nselfhost-render.onrender.com"
      - key: N8N_EDITOR_BASE_URL
        value: "https://n8nselfhost-render.onrender.com"
      - key: GENERIC_TIMEZONE
        value: "Asia/Bangkok"
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "${SUPABASE_DB_HOST}"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "${SUPABASE_DB_NAME}"
      - key: DB_POSTGRESDB_USER
        value: "${SUPABASE_DB_USER}"
      - key: DB_POSTGRESDB_PASSWORD
        value: "${SUPABASE_DB_PASSWORD}"
      - key: DB_POSTGRESDB_SCHEMA
        value: "public"
      - key: DB_POSTGRESDB_SSL
        value: "true"
